<?php

namespace CatalogueBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository {

    public function getAllCategoriesWithImage() {


        $qb = $this->createQueryBuilder('cat')
                ->leftJoin('cat.image', 'i')
                ->addSelect('i')
                ->orderBy('cat.titre', 'ASC');

        $query = $qb->getQuery();
        return $query->getResult();
    }

    public function getFullCategorie($id) {
        $qb = $this->createQueryBuilder('cat')
                ->leftJoin('cat.image', 'i')
                ->addSelect('i')
                ->leftJoin('cat.produits', 'p')
                ->addSelect('p')
                ->leftJoin('p.image', 'pi')
                ->addselect('pi')
                ->leftJoin('p.evaluation', 'pe')
                ->addselect('pe')
                ->where('cat.id = :id')
                ->setParameter('id', $id)
        ;
        return $qb->getQuery()->getSingleResult();
    }

}
