<?php

namespace CatalogueBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository {

    public function getFullProduit($id) {
        $qb = $this->createQueryBuilder('p')
                ->leftJoin('p.image', 'i')
                ->addSelect('i')
                ->leftJoin('p.categories', 'cat')
                ->addSelect('cat')
                ->leftJoin('cat.image', 'cati')
                ->addselect('cati')
                ->leftJoin('p.evaluation', 'e')
                ->addselect('e')
                ->where('p.id = :id')
                ->setParameter('id', $id)
        ;
        return $qb->getQuery()->getSingleResult();
    }

}
