<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository {

    public function getArticlesDeLAnneeEnCours() {
//$querybuilder = $this->_em->createQueryBuilder()->select('a')->from('AppBundle:Article', 'a');
//OU
        $querybuilder = $this->createQueryBuilder('a');
//        $querybuilder->where('a.publication = :publication')
//                ->setParameter('publication', '1')
//                ->andWhere('YEAR(a.date) = :annee')
//                ->setParameter('annee', 2015);

        $date = new \DateTime();
        $annee = $date->format('Y');
        $querybuilder->where('a.publication = :publication')
                ->setParameter('publication', 1)
                ->andWhere('a.date >= :annee')
                ->setParameter('annee', $annee)
                ->orderBy('a.date', 'DESC');


        $query = $querybuilder->getQuery();
        return $query->getResult();
    }

    public function getArticles() {
        $date = new \DateTime();
        $annee = $date->format('Y');
        $qb = $this->createQueryBuilder('a')
                ->leftJoin('a.image', 'i')
                ->addSelect('i')
                ->leftJoin('a.categories', 'c')
                ->addSelect('c')
                ->Where('a.publication = :publication')
                ->setParameter('publication', 1)
                ->andWhere('a.date >= :annee')
                ->setParameter('annee', $annee)
                ->orderBy('a.date', 'DESC');
        $query = $qb->getQuery();
        return $query->getResult();
    }

}
