app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
catalogue:
    resource: "@CatalogueBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"