# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    longueur_extrait : 200
    mode_maintenance : false
#    parameter_name: value

services:
    app_extrait:
        class: AppBundle\Services\Extrait
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
        arguments: ["%longueur_extrait%", "(...)"]
        tags:
            - {name: twig.extension}
            
    app.maintenance:
        class: AppBundle\Listener\MaintenanceListener
        arguments:
            [ "%mode_maintenance%", @templating ]
        tags:
            - {name: kernel.event_listener, event: kernel.response, method: onKernelResponse}
            
    appbundle_user.registration.form.type:
        class: AppBundle\Form\UserType
        arguments: [%fos_user.model.user.class%]
        tags:
            - {name: form.type, alias: appbundle_user }
            

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@doctrine","@translator"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu

                
