# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    longueur_extrait : 200
#    parameter_name: value

services:
    app_extrait:
        class: AppBundle\Services\Extrait
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
        arguments: ["%longueur_extrait%", "(...)"]
