# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    longueur_extrait : 200
    mode_maintenance : false
#    parameter_name: value

services:
    app_extrait:
        class: AppBundle\Services\Extrait
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
        arguments: ["%longueur_extrait%", "(...)"]
        tags:
            - {name: twig.extension}
            
    app.maintenance:
        class: AppBundle\Listener\MaintenanceListener
        arguments:
            [ "%mode_maintenance%", @templating ]
        tags:
            - {name: kernel.event_listener, event: kernel.response, method: onKernelResponse}
